In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv(r"C:\Users\WELCOME\OneDrive\Desktop\Hackathon\Student_drop_out\Ouput.csv")

In [59]:
df['Target'].unique()

array([0, 1], dtype=int64)

In [60]:
df = df.iloc[:,1:]

In [61]:
df

Application order  Course  Daytime/evening attendance  \
0                     5       2                           1   
1                     2      15                           1   
2                     1      12                           1   
3                     1      14                           1   
4                     1      12                           1   
...                 ...     ...                         ...   
2432                  1       8                           1   
2433                  1       5                           1   
2434                  6      15                           1   
2435                  1      12                           1   
2436                  1       9                           1   

      Mother's occupation  Father's occupation  Displaced  \
0                       6                   10          1   
1                       6                    4          1   
2                       8                   11          1   
3                       6                    8          1   
4                      10                   10          1   
...                   ...                  ...        ...   
2432                    4                    6          1   
2433                   10                   10          1   
2434                    6                    5          0   
2435                   10                   10          1   
2436                    8                    5          1   

      Tuition fees up to date  Scholarship holder  International  \
0                           1                   0              0   
1                           1                   0              0   
2                           1                   1              0   
3                           1                   0              0   
4                           1                   1              0   
...                       ...                 ...            ...   
2432                        1                   0              0   
2433                        1                   1              0   
2434                        1                   0              0   
2435                        1                   1              0   
2436                        1                   1              0   

      Curricular units 1st sem (credited)  ...  \
0                                       0  ...   
1                                       0  ...   
2                                       0  ...   
3                                       0  ...   
4                                       0  ...   
...                                   ...  ...   
2432                                    0  ...   
2433                                    0  ...   
2434                                    0  ...   
2435                                    0  ...   
2436                                    0  ...   

      Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                       0                          0.000000   
1                                       6                         13.428571   
2                                       7                         13.300000   
3                                       6                         12.333333   
4                                       7                         13.214286   
...                                   ...                               ...   
2432                                    5                         11.800000   
2433                                    6                         13.833333   
2434                                    5                         13.600000   
2435                                    7                         14.912500   
2436                                    5                         13.800000   

      Curricular units 2nd sem (credited)  \
0                                       0   
1                                       0   
2             

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2437 entries, 0 to 2436
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Application order                       2437 non-null   int64  
 1   Course                                  2437 non-null   int64  
 2   Daytime/evening attendance              2437 non-null   int64  
 3   Mother's occupation                     2437 non-null   int64  
 4   Father's occupation                     2437 non-null   int64  
 5   Displaced                               2437 non-null   int64  
 6   Tuition fees up to date                 2437 non-null   int64  
 7   Scholarship holder                      2437 non-null   int64  
 8   International                           2437 non-null   int64  
 9   Curricular units 1st sem (credited)     2437 non-null   int64  
 10  Curricular units 1st sem (enrolled)     2437 non-null   int6

In [63]:
df.isnull().sum()

Application order                         0
Course                                    0
Daytime/evening attendance                0
Mother's occupation                       0
Father's occupation                       0
Displaced                                 0
Tuition fees up to date                   0
Scholarship holder                        0
International                             0
Curricular units 1st sem (credited)       0
Curricular units 1st sem (enrolled)       0
Curricular units 1st sem (evaluations)    0
Curricular units 1st sem (approved)       0
Curricular units 1st sem (grade)          0
Curricular units 2nd sem (credited)       0
Curricular units 2nd sem (enrolled)       0
Curricular units 2nd sem (evaluations)    0
Curricular units 2nd sem (approved)       0
Curricular units 2nd sem (grade)          0
Unemployment rate                         0
GDP                                       0
Target                                    0
dtype: int64

In [64]:
import matplotlib.pyplot as plt
import seaborn as sns
df.sample()

Application order  Course  Daytime/evening attendance  \
2004                  1       6                           1   

      Mother's occupation  Father's occupation  Displaced  \
2004                    5                   10          1   

      Tuition fees up to date  Scholarship holder  International  \
2004                        1                   1              0   

      Curricular units 1st sem (credited)  ...  \
2004                                    0  ...   

      Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
2004                                    4                              12.0   

      Curricular units 2nd sem (credited)  \
2004                                    0   

      Curricular units 2nd sem (enrolled)  \
2004                                    5   

      Curricular units 2nd sem (evaluations)  \
2004                                       8   

      Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
2004                                    5                         13.333333   

      Unemployment rate   GDP  Target  
2004               10.8  1.74       1  

[1 rows x 22 columns]

In [65]:
df.shape

(2437, 22)

In [77]:
df

Application order  Course  Daytime/evening attendance  \
0                     5       2                           1   
1                     2      15                           1   
2                     1      12                           1   
3                     1      14                           1   
4                     1      12                           1   
...                 ...     ...                         ...   
2432                  1       8                           1   
2433                  1       5                           1   
2434                  6      15                           1   
2435                  1      12                           1   
2436                  1       9                           1   

      Mother's occupation  Father's occupation  Displaced  \
0                       6                   10          1   
1                       6                    4          1   
2                       8                   11          1   
3                       6                    8          1   
4                      10                   10          1   
...                   ...                  ...        ...   
2432                    4                    6          1   
2433                   10                   10          1   
2434                    6                    5          0   
2435                   10                   10          1   
2436                    8                    5          1   

      Tuition fees up to date  Scholarship holder  International  \
0                           1                   0              0   
1                           1                   0              0   
2                           1                   1              0   
3                           1                   0              0   
4                           1                   1              0   
...                       ...                 ...            ...   
2432                        1                   0              0   
2433                        1                   1              0   
2434                        1                   0              0   
2435                        1                   1              0   
2436                        1                   1              0   

      Curricular units 1st sem (credited)  ...  \
0                                       0  ...   
1                                       0  ...   
2                                       0  ...   
3                                       0  ...   
4                                       0  ...   
...                                   ...  ...   
2432                                    0  ...   
2433                                    0  ...   
2434                                    0  ...   
2435                                    0  ...   
2436                                    0  ...   

      Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                       0                          0.000000   
1                                       6                         13.428571   
2                                       7                         13.300000   
3                                       6                         12.333333   
4                                       7                         13.214286   
...                                   ...                               ...   
2432                                    5                         11.800000   
2433                                    6                         13.833333   
2434                                    5                         13.600000   
2435                                    7                         14.912500   
2436                                    5                         13.800000   

      Curricular units 2nd sem (credited)  \
0                                       0   
1                                       0   
2             

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df.shape

(2437, 22)

In [78]:
X = df.drop('Target', axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Names=list(X_train.columns.values)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [79]:
X_train

array([[ 0.70496254, -0.07519095,  0.        , ...,  0.07347614,
         0.40444762, -0.79492647],
       [-0.67536003, -0.07519095,  0.        , ...,  0.29259277,
        -0.20877595,  0.88378038],
       [-0.67536003, -1.41776905,  0.        , ...,  0.30354861,
         0.40444762, -0.79492647],
       ...,
       [-0.67536003, -1.14925343,  0.        , ...,  0.49527566,
        -1.55020249,  0.1166294 ],
       [-0.67536003,  1.26738714,  0.        , ...,  0.40899849,
        -0.20877595,  0.88378038],
       [-0.67536003,  0.46184028,  0.        , ...,  0.07028069,
        -1.55020249,  0.1166294 ]])

In [80]:
from sklearn.linear_model import LogisticRegression

In [72]:
lr = LogisticRegression()

In [73]:
lr.fit(X_train,y_train)

LogisticRegression()

In [74]:
y_pred = lr.predict(X_test)

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
accuracy_score(y_test,y_pred)

0.9006211180124224

In [101]:
lr.predict(X_test[0].reshape(1,-1))

array([1], dtype=int64)

In [98]:
X_test[0].reshape(-1,1)

array([[ 1.39512382e+00],
       [ 1.93324664e-01],
       [ 0.00000000e+00],
       [-5.91115601e-01],
       [-6.41067014e-01],
       [ 7.52475122e-01],
       [ 0.00000000e+00],
       [-6.93501073e-01],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 7.09205085e-02],
       [-1.00060228e-01],
       [ 5.55255896e-01],
       [ 1.42280738e-01],
       [ 0.00000000e+00],
       [ 7.00700999e-04],
       [-3.84133159e-01],
       [ 5.38960653e-01],
       [ 3.29112213e-01],
       [ 8.64365291e-01],
       [ 3.28724085e-01]])